language: go
go:
  - 1.9
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get -y install libgtk-3-dev
  - go get github.com/mattn/goveralls
install:
  - # do nothing here 
script:
  - go get -v -tags gtk_3_10 github.com/gotk3/gotk3/gtk
  - go get -v github.com/go-ini/ini
  - go get -v github.com/urfave/cli
  - go get -v github.com/kylelemons/godebug/pretty
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -tags gtk_3_10 -covermode=count -coverprofile=profile.cov
  - $HOME/gopath/bin/goveralls -v -coverprofile=profile.cov -service=travis-ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
